TaskrP/taskr/urls.py
from django.conf.urls import url
from accounts.views import LoginView, LogoutView, RegisterView
from django.contrib.auth.decorators import login_required
from .views import IndexView, TaskListCreateView, TaskListActiveView, TaskListArchivedView, TaskDetailCompleteView

urlpatterns = [
    url(r'^auth/login/$', LoginView.as_view(template_name='auth/login.html'), name='auth-login'),
    url(r'^auth/logout/$', LogoutView.as_view(), name='auth-logout'),
    url(r'^auth/register/$', RegisterView.as_view(template_name='auth/register.html'), name='auth-register'),

    # url(r'^profile/$', ProfileView.as_view(), name='author-profile-self' ),
    # url(r'^profile/(?P<pk>[1-9][0-9]*)/$', ProfileView.as_view(), name='author-profile'),

    url(r'^task/list/$', TaskListActiveView.as_view(), name='task-list'),
    url(r'^task/archive/$', TaskListArchivedView.as_view(), name='task-archive'),
    url(r'^task/(?P<pk>[1-9][0-9]*)/$', TaskDetailCompleteView.as_view(), name='task-detail'),

    url(r'^users/(?P<pk>[1-9][0-9]*)/', IndexView.as_view(), name='user-profile'),

    url(r'^task/$', TaskListCreateView.as_view(), name='home'),
    url(r'^$', IndexView.as_view(), name='index'),
]

TaskrP/taskrp/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
admin.autodiscover()

from taskr_rest import urls as taskr_rest_urls
from taskr import urls as taskr_urls

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^api/', include(taskr_rest_urls)),
    url(r'^', include(taskr_urls, namespace='taskr')),
)

TaskrP/taskr/models.py
from django.db import models
from django.utils import timezone
from django.core.urlresolvers import reverse
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin


class AuthorProfile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, primary_key=True)
    name = models.CharField(max_length=30)

    def __str__(self):
        return u'%s' % self.user

    def get_absolute_url(self):
        return reverse('taskr:user-profile', kwargs={'pk': self.user.id})


# class Tag(models.Model):
#     name = models.CharField(max_length=30)
#     owner = models.OneToOneField(settings.AUTH_USER_MODEL)


# class Group(models.Model):
#     name = models.CharField(max_length=30)
#     owner = models.OneToOneField(settings.AUTH_USER_MODEL)
#     members = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='members')


class Task(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, unique=False)
    title = models.CharField(max_length=255)
    # content = models.TextField(blank=True, max_length=255, default='')
    completed = models.BooleanField(default=False)
    deadline = models.DateTimeField(null=True, blank=True, default=None)
    pub_date = models.DateTimeField(auto_now_add=True, editable=False)
    edit_date = models.DateTimeField(auto_now_add=True, auto_now=True, editable=False)
    # tag = models.ManyToManyField(Tag, related_name='tags', null=True, blank=True, default=None)
    # group = models.ForeignKey(Group, blank=True, default=None)

    absolute_url = None

    def __str__(self):
        return u'%s' % (self.title)

    def toggle_complete(self, commit=True):
        self.completed = not self.completed

        if commit:
            self.save()

    def is_near_deadline(self, days=1):
        if self.is_past_deadline():
            return False
        return (self.deadline-timezone.timedelta(days=days)) < timezone.now()

    def is_past_deadline(self):
        return (self.deadline < timezone.now()) if self.deadline else False

    def get_absolute_url(self):
        return reverse('taskr:task-detail', kwargs={'pk': self.id })

TaskrP/taskr/forms.py
from django import forms
from .models import Task


class TaskCreateForm(forms.ModelForm):
    title = forms.CharField(help_text=u'')
    deadline = forms.DateTimeField(help_text=u'Optional, format: yyyy/mm/dd (HH:MM)',
                                   widget=forms.DateTimeInput(attrs={'id': 'datepicker'}),
                                   required=False)

    class Meta:
        model = Task
        fields = ['title', 'deadline']


class TaskCompleteForm(forms.Form):
    id = forms.IntegerField(required=True, widget=forms.HiddenInput())
    author_id = forms.IntegerField(required=True, widget=forms.HiddenInput())

    class Meta:
        fields = ['id', 'author_id']

    def is_valid(self):
        is_valid = super(TaskCompleteForm, self).is_valid()
        if is_valid:
            try:
                id = self.cleaned_data['id']
                author_id = self.cleaned_data['author_id']
                Task.objects.get(pk=id, author_id=author_id)
                return True
            except Task.DoesNotExist:
                pass
        return False

TaskrP/taskr/views/_mixin.py
from django.views.generic.base import ContextMixin

__author__ = 'Alex'


class FilterMultipleObjectMixin(ContextMixin):
    """ Mixin that populates context with filtered data from a queryset """
    filter = None

    offset = None
    limit = None

    context_object_name = None

    def get_offset(self):
        return self.offset if self.offset  else 0

    def get_limit(self):
        return self.limit if self.limit  else self.get_queryset().count()

    def get_filter(self):
        return self.filter if self.filter else {}

    def get_context_object_name(self):
        return self.context_object_name if self.context_object_name else 'object_list'

    def get_filtered_queryset(self):
        queryset = self.get_queryset()

        # Compose filter
        filter = self.get_filter()

        # Calculate offset and limit
        offset = self.get_offset()
        limit = self.get_limit()

        return queryset.filter(**filter)[offset:limit]

    def get_context_data(self, **kwargs):
        """ Returns context data with filtered object list  """
        queryset = self.get_filtered_queryset()

        # Create context
        context = {
            self.get_context_object_name(): queryset
        }
        context.update(**kwargs)

        # Follow up grand-parent's implementation
        return super(FilterMultipleObjectMixin, self).get_context_data(**context)


class UserFilterMultipleObjectMixin(FilterMultipleObjectMixin):
    """ Mixin that populates context with filtered data, with the currently logged user as value, from a queryset """

    attr = None

    def get_filter(self):
        filter = {}
        if self.attr:
            filter[self.attr] = self.request.user
        return filter

TaskrP/taskr/views/_task.py
from django.shortcuts import get_object_or_404
from django.utils.decorators import method_decorator

__author__ = 'Alex'

from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse_lazy
from django.views.generic import TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.edit import FormMixin, CreateView
from ._mixin import UserFilterMultipleObjectMixin
from ..models import Task
from ..forms import TaskCreateForm, TaskCompleteForm


class TaskListCreateView(UserFilterMultipleObjectMixin, CreateView):
    form_class = TaskCreateForm
    queryset = Task.objects.filter(completed=False)
    template_name = 'home.html'
    context_object_name = 'tasks'
    success_url = reverse_lazy('taskr:home')
    attr = 'author_id'
    offset = None
    limit = 10

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(TaskListCreateView, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        task = form.save(commit=False)
        task.author = self.request.user
        return super(TaskListCreateView, self).form_valid(form)


class TaskListActiveView(UserFilterMultipleObjectMixin, TemplateView):
    queryset = Task.objects.filter(completed=False)
    template_name = 'task/list.html'
    context_object_name = 'tasks'
    attr = 'author_id'

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(TaskListActiveView, self).dispatch(request, *args, **kwargs)

    def get_queryset(self):
        return self.queryset


class TaskListArchivedView(TaskListActiveView):
    queryset = Task.objects.filter(completed=True)
    template_name = 'task/archive.html'


class TaskDetailCompleteView(FormMixin, DetailView):
    form_class = TaskCompleteForm
    template_name = 'task/detail.html'
    model = Task
    context_object_name = 'task'

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        self.object = get_object_or_404(self.model, pk=kwargs['pk'], author=request.user)
        self.success_url = reverse_lazy('taskr:task-detail', kwargs={'pk': kwargs['pk']})
        return super(TaskDetailCompleteView, self).dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        form = self.get_form(self.form_class)
        if form.is_valid():
            return self.form_valid(form)
        return super(TaskDetailCompleteView, self).get(request, *args, **kwargs)

    def form_valid(self, form):
        task = Task.objects.get(pk=form.cleaned_data['id'])
        task.toggle_complete(commit=False)
        task.save()
        return super(TaskDetailCompleteView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(TaskDetailCompleteView, self).get_context_data(**kwargs)
        form = self.get_form(self.form_class)
        if form:
            context['form'] = form
        context.update(kwargs)
        return super(TaskDetailCompleteView, self).get_context_data(**context)

TaskrP/taskr/templates/base.html
{% extends 'base/bootstrap3.html' %}

{% load bootstrap3 %}
{% load url from future %}
{% load static from staticfiles %}

{% block bootstrap3_extra_head %}
<link rel="stylesheet" title="taskr" href="{% static 'css/main.css' %}" />
{% block extra_head %}{% endblock %}
{% endblock %}

{% block bootstrap3_content %}
{#<div id="gotop">#}
{#    <a href="#top" class="btn btn-xs btn-info">#}
{#        <small>Go to top <span class="glyphicon glyphicon-arrow-up"></span></small>#}
{#    </a>#}
{#</div>#}
<div id="container" class="container col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3">
    <div id="header" class="row">
        <div class="navbar navbar-default" role="navigation">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <a class="navbar-brand" href="{% url 'taskr:index' %}">
                    <strong>Taskr!</strong>
                    <small><sup class="text-muted">BETA</sup></small>
                </a>
            </div>

            <div id="navbar-collapse" class="navbar-collapse collapse ">
            {% include 'base/_navbar_contents.html' %}
            </div>
        </div>
    </div>

    {% bootstrap_messages %}

    <div id="content" class="row">
        <div class="{% block content_class %}col-lg-10 col-lg-offset-1{% endblock %}">
        {% block content %}(no content){% endblock %}
        </div>
    </div>

    <div class="row">
        <hr />
    </div>

    <div id="footer" class="row">
        {% include 'base/_footer_contents.html' %}
    </div>
</div>
{% endblock %}

TaskrP/taskr/templates/home.html
{% extends 'base.html' %}

{% load bootstrap3 %}

{% block title %}Home{% endblock %}

{% block content %}
<div class="row-fluid">
    <h2>Latest tasks</h2>
    {% include 'task/_list.html' with tasks=tasks only %}
</div>
<div class="row-fluid">
    <hr />
</div>
<div class="row-fluid ">
    <h2 id="createtask">New task</h2>
    <form class="form form-horizontal" method="post" action="{% url 'taskr:home' %}">
        {% bootstrap_form form layout='horizontal' label_class='col-md-2' field_class='col-md-8' %}
        {% csrf_token %}
        {% buttons layout='horizontal' %}{% bootstrap_button 'New Task' 'submit' %}{% endbuttons %}
    </form>
</div>
{% endblock %}

{% block extra_script %}
<script>
$('#datepicker').datepicker({
    format      : "yyyy/mm/dd",
    todayBtn    : "linked",
    language    : "en",
    autoclose   : true,
    weekStart   : 1
});
</script>
{% endblock %}

TaskrP/taskr/templates/index.html
{% extends 'base.html' %}

{% block title %}Welcome!{% endblock %}

{% block content %}
    {% if not user.is_authenticated %}
    <div class="jumbotron">
        <h1><span class="text-primary">Taskr</span> + you = awesome!</h1>
        <p>Taskr let's you manage your tasks, be them personal or professional, with absolute ease.</p>
        <p>Simple by design, try it now...</p>
        <p class="text-center"><a href="{% url 'taskr:auth-register' %}" class="btn btn-lg btn-primary">Sign me up!</a></p>
    </div>
    {% endif %}

    <div class="row-fluid">
        <div class="col-md-4">
            <h3>Placeholder 1</h3>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                Donec et tincidunt ligula, ut aliquam leo.
                Sed ut urna eu augue fringilla tempor a vel tellus.
                Cras quis eleifend quam. Vestibulum.
            </p>
        </div>
         <div class="col-md-4">
            <h3>Placeholder 2</h3>
            <p>
                Etiam sed purus ipsum. Phasellus posuere sed libero a tincidunt.
                Sed sit amet feugiat libero. Nulla non laoreet tellus.
                Fusce nec turpis pharetra, condimentum purus et, tempor nunc.
                Duis tristique.
            </p>
        </div>
         <div class="col-md-4">
            <h3>Placeholder 3</h3>
            <p>
                Ut sit amet nulla sit amet turpis blandit pharetra.
                Pellentesque interdum vestibulum dui, at gravida mi.
                Mauris rhoncus risus et bibendum porta.
                Nullam quis eros tempor, pharetra metus nec, aliquam.
            </p>
        </div>
    </div>
{% endblock %}